# fly.toml app configuration file generated for tr-blog on 2023-07-03T20:36:18-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "tr-blog"
primary_region = "sea"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
